@host = localhost:5000


// Get All Todos
GET http://{{host}}/todos/ HTTP/1.1
content-type: application/json

###

// Get Todo By ID
GET http://{{host}}/todos/15 HTTP/1.1
content-type: application/json

###

// Delete Todo
DELETE http://{{host}}/todos/15 HTTP/1.1
content-type: application/json

###

// Create Todo
POST http://{{host}}/todos/ HTTP/1.1
content-type: application/json
    
{
    "title": "test-todo",
    "isDone": false
}

###

// Create Todo -> short title - ment to failed
POST http://{{host}}/todos/ HTTP/1.1
content-type: application/json
    
{
    "title": "2c",
    "isDone": false
}

###

// Create Todo -> long title - ment to failed
POST http://{{host}}/todos/ HTTP/1.1
content-type: application/json

{
    "title": "this is too long title for the todo and need to be rejected",
    "isDone": true
}

###

// Update Todo
PUT http://{{host}}/todos/2 HTTP/1.1
content-type: application/json

{
    "title": "updated-todo",
    "isDone": true
}

###

// Update Todo -> short title - ment to failed
PUT http://{{host}}/todos/2 HTTP/1.1
content-type: application/json

{
    "title": "2c",
    "isDone": true
}

###

// Update Todo -> long title - ment to failed
PUT http://{{host}}/todos/2 HTTP/1.1
content-type: application/json

{
    "title": "this is too long title for the todo and need to be rejected",
    "isDone": true
}
